// Phonetic help system for struggling readers

import type { GradeLevel } from './stories';

// Phonetic breakdown of common words
// Format: word -> { phonetic: "how to say it", hint: "simpler words that sound similar" }
interface PhoneticHelp {
  phonetic: string;
  hint: string;
  syllables: string[];
}

// Common word phonetics organized by complexity
const phoneticDictionary: Record<string, PhoneticHelp> = {
  // Simple words (JK/SK)
  'the': { phonetic: 'thuh', hint: 'like "duh" with a "th"', syllables: ['the'] },
  'a': { phonetic: 'uh', hint: 'like when you think "uh..."', syllables: ['a'] },
  'is': { phonetic: 'iz', hint: 'like "fizz" without the "f"', syllables: ['is'] },
  'it': { phonetic: 'it', hint: 'rhymes with "sit"', syllables: ['it'] },
  'in': { phonetic: 'in', hint: 'rhymes with "win"', syllables: ['in'] },
  'on': { phonetic: 'on', hint: 'rhymes with "gone"', syllables: ['on'] },
  'up': { phonetic: 'up', hint: 'rhymes with "cup"', syllables: ['up'] },
  'my': { phonetic: 'my', hint: 'rhymes with "fly"', syllables: ['my'] },
  'me': { phonetic: 'mee', hint: 'rhymes with "see"', syllables: ['me'] },
  'we': { phonetic: 'wee', hint: 'rhymes with "see"', syllables: ['we'] },
  'he': { phonetic: 'hee', hint: 'rhymes with "see"', syllables: ['he'] },
  'she': { phonetic: 'shee', hint: 'like "he" with "sh"', syllables: ['she'] },
  'and': { phonetic: 'and', hint: 'like "hand" without "h"', syllables: ['and'] },
  'can': { phonetic: 'kan', hint: 'rhymes with "man"', syllables: ['can'] },
  'see': { phonetic: 'see', hint: 'rhymes with "me"', syllables: ['see'] },
  'saw': { phonetic: 'saw', hint: 'rhymes with "paw"', syllables: ['saw'] },
  'big': { phonetic: 'big', hint: 'rhymes with "pig"', syllables: ['big'] },
  'run': { phonetic: 'run', hint: 'rhymes with "sun"', syllables: ['run'] },
  'fun': { phonetic: 'fun', hint: 'rhymes with "sun"', syllables: ['fun'] },
  'sun': { phonetic: 'sun', hint: 'rhymes with "run"', syllables: ['sun'] },
  'red': { phonetic: 'red', hint: 'rhymes with "bed"', syllables: ['red'] },
  'cat': { phonetic: 'kat', hint: 'rhymes with "hat"', syllables: ['cat'] },
  'dog': { phonetic: 'dog', hint: 'rhymes with "log"', syllables: ['dog'] },
  'pet': { phonetic: 'pet', hint: 'rhymes with "wet"', syllables: ['pet'] },
  'ball': { phonetic: 'bawl', hint: 'rhymes with "tall"', syllables: ['ball'] },
  'have': { phonetic: 'hav', hint: 'like "has" but ends with "v"', syllables: ['have'] },
  'love': { phonetic: 'luv', hint: 'rhymes with "of"', syllables: ['love'] },
  'with': { phonetic: 'with', hint: 'rhymes with "myth"', syllables: ['with'] },
  'soft': { phonetic: 'sawft', hint: 'like "off" with "s" and "t"', syllables: ['soft'] },
  'happy': { phonetic: 'hap-ee', hint: 'hap like "cap" + ee', syllables: ['hap', 'py'] },
  'little': { phonetic: 'lit-ul', hint: 'lit like "sit" + ul', syllables: ['lit', 'tle'] },
  'water': { phonetic: 'waw-ter', hint: 'waw like "paw" + ter', syllables: ['wa', 'ter'] },
  'goes': { phonetic: 'gohz', hint: 'like "toes" with a "g"', syllables: ['goes'] },
  'kick': { phonetic: 'kik', hint: 'rhymes with "stick"', syllables: ['kick'] },

  // SK words
  'frog': { phonetic: 'frog', hint: 'rhymes with "log"', syllables: ['frog'] },
  'log': { phonetic: 'log', hint: 'rhymes with "dog"', syllables: ['log'] },
  'fly': { phonetic: 'fly', hint: 'rhymes with "sky"', syllables: ['fly'] },
  'hop': { phonetic: 'hop', hint: 'rhymes with "top"', syllables: ['hop'] },
  'got': { phonetic: 'got', hint: 'rhymes with "hot"', syllables: ['got'] },
  'yellow': { phonetic: 'yel-oh', hint: 'yel + oh', syllables: ['yel', 'low'] },
  'warm': { phonetic: 'worm', hint: 'like the animal "worm"', syllables: ['warm'] },
  'play': { phonetic: 'play', hint: 'rhymes with "day"', syllables: ['play'] },
  'good': { phonetic: 'gud', hint: 'rhymes with "would"', syllables: ['good'] },
  'night': { phonetic: 'nite', hint: 'rhymes with "light"', syllables: ['night'] },
  'soon': { phonetic: 'soon', hint: 'rhymes with "moon"', syllables: ['soon'] },
  'fish': { phonetic: 'fish', hint: 'rhymes with "wish"', syllables: ['fish'] },
  'blue': { phonetic: 'bloo', hint: 'rhymes with "new"', syllables: ['blue'] },
  'small': { phonetic: 'smawl', hint: 'rhymes with "tall"', syllables: ['small'] },
  'fast': { phonetic: 'fast', hint: 'rhymes with "last"', syllables: ['fast'] },
  'friend': { phonetic: 'frend', hint: 'rhymes with "end"', syllables: ['friend'] },
  'swims': { phonetic: 'swimz', hint: 'swim + z', syllables: ['swims'] },
  'comes': { phonetic: 'kumz', hint: 'like "hums"', syllables: ['comes'] },
  'makes': { phonetic: 'mayks', hint: 'rhymes with "takes"', syllables: ['makes'] },
  'feel': { phonetic: 'feel', hint: 'rhymes with "wheel"', syllables: ['feel'] },

  // Grade 1 words
  'once': { phonetic: 'wuns', hint: 'sounds like "ones"', syllables: ['once'] },
  'there': { phonetic: 'thair', hint: 'rhymes with "where"', syllables: ['there'] },
  'was': { phonetic: 'wuz', hint: 'rhymes with "buzz"', syllables: ['was'] },
  'dragon': { phonetic: 'drag-un', hint: 'drag + un', syllables: ['drag', 'on'] },
  'who': { phonetic: 'hoo', hint: 'like an owl "hoo"', syllables: ['who'] },
  'lived': { phonetic: 'livd', hint: 'live + d', syllables: ['lived'] },
  'cave': { phonetic: 'kayv', hint: 'rhymes with "wave"', syllables: ['cave'] },
  'green': { phonetic: 'green', hint: 'rhymes with "mean"', syllables: ['green'] },
  'wings': { phonetic: 'wingz', hint: 'wing + z', syllables: ['wings'] },
  'scary': { phonetic: 'skair-ee', hint: 'scare + ee', syllables: ['scar', 'y'] },
  'wanted': { phonetic: 'won-tid', hint: 'want + id', syllables: ['want', 'ed'] },
  'children': { phonetic: 'chil-drun', hint: 'child + run', syllables: ['chil', 'dren'] },
  'afraid': { phonetic: 'uh-frayd', hint: 'uh + fraid', syllables: ['a', 'fraid'] },
  'played': { phonetic: 'playd', hint: 'play + d', syllables: ['played'] },
  'together': { phonetic: 'tuh-geth-er', hint: 'to + geth + er', syllables: ['to', 'geth', 'er'] },
  'afternoon': { phonetic: 'af-ter-noon', hint: 'after + noon', syllables: ['af', 'ter', 'noon'] },
  'many': { phonetic: 'men-ee', hint: 'sounds like "any" with m', syllables: ['man', 'y'] },
  'friends': { phonetic: 'frendz', hint: 'friend + z', syllables: ['friends'] },
  'rainbow': { phonetic: 'rayn-boh', hint: 'rain + bow', syllables: ['rain', 'bow'] },
  'beautiful': { phonetic: 'byoo-ti-ful', hint: 'beauty + ful', syllables: ['beau', 'ti', 'ful'] },
  'orange': { phonetic: 'or-inj', hint: 'or + inj', syllables: ['or', 'ange'] },
  'purple': { phonetic: 'per-pul', hint: 'per + pul', syllables: ['pur', 'ple'] },
  'garden': { phonetic: 'gar-din', hint: 'gar + din', syllables: ['gar', 'den'] },
  'flowers': { phonetic: 'flow-erz', hint: 'flow + ers', syllables: ['flow', 'ers'] },
  'started': { phonetic: 'star-tid', hint: 'start + id', syllables: ['start', 'ed'] },
  'different': { phonetic: 'dif-er-ent', hint: 'differ + ent', syllables: ['dif', 'fer', 'ent'] },
  'color': { phonetic: 'kul-er', hint: 'cull + er', syllables: ['col', 'or'] },
  'puppy': { phonetic: 'pup-ee', hint: 'pup + ee', syllables: ['pup', 'py'] },
  'today': { phonetic: 'tuh-day', hint: 'to + day', syllables: ['to', 'day'] },
  'brown': { phonetic: 'brown', hint: 'rhymes with "town"', syllables: ['brown'] },
  'fur': { phonetic: 'fer', hint: 'rhymes with "her"', syllables: ['fur'] },
  'nose': { phonetic: 'nohz', hint: 'rhymes with "toes"', syllables: ['nose'] },
  'tail': { phonetic: 'tayl', hint: 'rhymes with "mail"', syllables: ['tail'] },
  'wags': { phonetic: 'wagz', hint: 'wag + z', syllables: ['wags'] },
  'named': { phonetic: 'naymd', hint: 'name + d', syllables: ['named'] },
  'loves': { phonetic: 'luvz', hint: 'love + z', syllables: ['loves'] },
  'long': { phonetic: 'long', hint: 'rhymes with "song"', syllables: ['long'] },
  'naps': { phonetic: 'naps', hint: 'nap + s', syllables: ['naps'] },
  'give': { phonetic: 'giv', hint: 'rhymes with "live"', syllables: ['give'] },
  'food': { phonetic: 'food', hint: 'rhymes with "mood"', syllables: ['food'] },
  'every': { phonetic: 'ev-ree', hint: 'ev + ree', syllables: ['ev', 'ery'] },
  'best': { phonetic: 'best', hint: 'rhymes with "rest"', syllables: ['best'] },
  'forever': { phonetic: 'for-ev-er', hint: 'for + ever', syllables: ['for', 'ev', 'er'] },

  // Grade 2 words
  'always': { phonetic: 'awl-wayz', hint: 'all + ways', syllables: ['al', 'ways'] },
  'dreamed': { phonetic: 'dreemd', hint: 'dream + d', syllables: ['dreamed'] },
  'visiting': { phonetic: 'viz-it-ing', hint: 'visit + ing', syllables: ['vis', 'it', 'ing'] },
  'stars': { phonetic: 'starz', hint: 'star + z', syllables: ['stars'] },
  'something': { phonetic: 'sum-thing', hint: 'some + thing', syllables: ['some', 'thing'] },
  'amazing': { phonetic: 'uh-may-zing', hint: 'amaze + ing', syllables: ['a', 'maz', 'ing'] },
  'happened': { phonetic: 'hap-ind', hint: 'happen + d', syllables: ['hap', 'pened'] },
  'sparkly': { phonetic: 'spar-klee', hint: 'sparkle + ee', syllables: ['spar', 'kly'] },
  'spaceship': { phonetic: 'spays-ship', hint: 'space + ship', syllables: ['space', 'ship'] },
  'landed': { phonetic: 'lan-did', hint: 'land + id', syllables: ['land', 'ed'] },
  'backyard': { phonetic: 'bak-yard', hint: 'back + yard', syllables: ['back', 'yard'] },
  'friendly': { phonetic: 'frend-lee', hint: 'friend + lee', syllables: ['friend', 'ly'] },
  'alien': { phonetic: 'ay-lee-un', hint: 'a + lee + un', syllables: ['a', 'li', 'en'] },
  'invited': { phonetic: 'in-vy-tid', hint: 'invite + id', syllables: ['in', 'vit', 'ed'] },
  'aboard': { phonetic: 'uh-bord', hint: 'a + board', syllables: ['a', 'board'] },
  'zoomed': { phonetic: 'zoomd', hint: 'zoom + d', syllables: ['zoomed'] },
  'planets': { phonetic: 'plan-its', hint: 'plan + its', syllables: ['plan', 'ets'] },
  'saturn': { phonetic: 'sat-ern', hint: 'sat + urn', syllables: ['sat', 'urn'] },
  'rings': { phonetic: 'ringz', hint: 'ring + z', syllables: ['rings'] },
  'waved': { phonetic: 'wayvd', hint: 'wave + d', syllables: ['waved'] },
  'astronauts': { phonetic: 'as-truh-nawts', hint: 'astro + nauts', syllables: ['as', 'tro', 'nauts'] },
  'station': { phonetic: 'stay-shun', hint: 'stay + shun', syllables: ['sta', 'tion'] },
  'twinkled': { phonetic: 'twink-uld', hint: 'twinkle + d', syllables: ['twin', 'kled'] },
  'diamonds': { phonetic: 'dy-mundz', hint: 'die + monds', syllables: ['dia', 'monds'] },
  'around': { phonetic: 'uh-round', hint: 'a + round', syllables: ['a', 'round'] },
  'smiled': { phonetic: 'smyld', hint: 'smile + d', syllables: ['smiled'] },
  'watching': { phonetic: 'woch-ing', hint: 'watch + ing', syllables: ['watch', 'ing'] },
  'beneath': { phonetic: 'bee-neeth', hint: 'be + neath', syllables: ['be', 'neath'] },
  'waves': { phonetic: 'wayvz', hint: 'wave + z', syllables: ['waves'] },
  'world': { phonetic: 'werld', hint: 'rhymes with "curled"', syllables: ['world'] },
  'alive': { phonetic: 'uh-lyv', hint: 'a + live', syllables: ['a', 'live'] },
  'colorful': { phonetic: 'kul-er-ful', hint: 'color + ful', syllables: ['col', 'or', 'ful'] },
  'through': { phonetic: 'throo', hint: 'sounds like "threw"', syllables: ['through'] },
  'coral': { phonetic: 'kor-ul', hint: 'core + ul', syllables: ['cor', 'al'] },
  'octopus': { phonetic: 'ok-tuh-pus', hint: 'octo + pus', syllables: ['oc', 'to', 'pus'] },
  'hides': { phonetic: 'hydz', hint: 'hide + z', syllables: ['hides'] },
  'among': { phonetic: 'uh-mung', hint: 'a + mung', syllables: ['a', 'mong'] },
  'rocks': { phonetic: 'roks', hint: 'rock + s', syllables: ['rocks'] },
  'turtle': { phonetic: 'ter-tul', hint: 'tur + tle', syllables: ['tur', 'tle'] },
  'glides': { phonetic: 'glydz', hint: 'glide + z', syllables: ['glides'] },
  'gracefully': { phonetic: 'grays-ful-ee', hint: 'grace + fully', syllables: ['grace', 'ful', 'ly'] },
  'dolphins': { phonetic: 'dol-finz', hint: 'doll + fins', syllables: ['dol', 'phins'] },
  'surface': { phonetic: 'ser-fis', hint: 'sur + face', syllables: ['sur', 'face'] },
  'whale': { phonetic: 'wayl', hint: 'rhymes with "tail"', syllables: ['whale'] },
  'sings': { phonetic: 'singz', hint: 'sing + z', syllables: ['sings'] },
  'deep': { phonetic: 'deep', hint: 'rhymes with "sleep"', syllables: ['deep'] },
  'jellyfish': { phonetic: 'jel-ee-fish', hint: 'jelly + fish', syllables: ['jel', 'ly', 'fish'] },
  'float': { phonetic: 'floht', hint: 'rhymes with "boat"', syllables: ['float'] },
  'glowing': { phonetic: 'gloh-ing', hint: 'glow + ing', syllables: ['glow', 'ing'] },
  'lanterns': { phonetic: 'lan-ternz', hint: 'lan + terns', syllables: ['lan', 'terns'] },
  'starfish': { phonetic: 'star-fish', hint: 'star + fish', syllables: ['star', 'fish'] },
  'sandy': { phonetic: 'san-dee', hint: 'sand + ee', syllables: ['sand', 'y'] },
  'ocean': { phonetic: 'oh-shun', hint: 'o + shun', syllables: ['o', 'cean'] },
  'floor': { phonetic: 'flor', hint: 'rhymes with "door"', syllables: ['floor'] },
  'holds': { phonetic: 'hohldz', hint: 'hold + z', syllables: ['holds'] },
  'secrets': { phonetic: 'see-krits', hint: 'secret + s', syllables: ['se', 'crets'] },
  'wonderful': { phonetic: 'wun-der-ful', hint: 'wonder + ful', syllables: ['won', 'der', 'ful'] },
  'creatures': { phonetic: 'kree-cherz', hint: 'creature + z', syllables: ['crea', 'tures'] },
  'discover': { phonetic: 'dis-kuv-er', hint: 'dis + cover', syllables: ['dis', 'cov', 'er'] },
  'treehouse': { phonetic: 'tree-hous', hint: 'tree + house', syllables: ['tree', 'house'] },
  'oak': { phonetic: 'ohk', hint: 'rhymes with "poke"', syllables: ['oak'] },
  'special': { phonetic: 'spesh-ul', hint: 'spesh + ul', syllables: ['spe', 'cial'] },
  'discovered': { phonetic: 'dis-kuv-erd', hint: 'discover + d', syllables: ['dis', 'cov', 'ered'] },
  'summer': { phonetic: 'sum-er', hint: 'sum + er', syllables: ['sum', 'mer'] },
  'climbed': { phonetic: 'klymd', hint: 'climb + d', syllables: ['climbed'] },
  'inside': { phonetic: 'in-syd', hint: 'in + side', syllables: ['in', 'side'] },
  'books': { phonetic: 'buks', hint: 'book + s', syllables: ['books'] },
  'everywhere': { phonetic: 'ev-ree-wair', hint: 'every + where', syllables: ['ev', 'ery', 'where'] },
  'adventure': { phonetic: 'ad-ven-cher', hint: 'advent + ure', syllables: ['ad', 'ven', 'ture'] },
  'knights': { phonetic: 'nyts', hint: 'sounds like "nights"', syllables: ['knights'] },
  'castles': { phonetic: 'kas-ulz', hint: 'castle + z', syllables: ['cas', 'tles'] },
  'suddenly': { phonetic: 'sud-un-lee', hint: 'sudden + lee', syllables: ['sud', 'den', 'ly'] },
  'began': { phonetic: 'bee-gan', hint: 'be + gan', syllables: ['be', 'gan'] },
  'spin': { phonetic: 'spin', hint: 'rhymes with "win"', syllables: ['spin'] },
  'stopped': { phonetic: 'stopt', hint: 'stop + t', syllables: ['stopped'] },
  'castle': { phonetic: 'kas-ul', hint: 'cass + ul', syllables: ['cas', 'tle'] },
  'princess': { phonetic: 'prin-ses', hint: 'prince + ess', syllables: ['prin', 'cess'] },
  'needed': { phonetic: 'nee-did', hint: 'need + id', syllables: ['need', 'ed'] },
  'help': { phonetic: 'help', hint: 'rhymes with "yelp"', syllables: ['help'] },
  'solved': { phonetic: 'solvd', hint: 'solve + d', syllables: ['solved'] },
  'mystery': { phonetic: 'mis-ter-ee', hint: 'mister + ee', syllables: ['mys', 'ter', 'y'] },
  'lost': { phonetic: 'lost', hint: 'rhymes with "cost"', syllables: ['lost'] },
  'crown': { phonetic: 'krown', hint: 'rhymes with "town"', syllables: ['crown'] },
  'magic': { phonetic: 'maj-ik', hint: 'madge + ick', syllables: ['mag', 'ic'] },
  'brought': { phonetic: 'brawt', hint: 'sounds like "bought"', syllables: ['brought'] },
  'safely': { phonetic: 'sayf-lee', hint: 'safe + lee', syllables: ['safe', 'ly'] },
  'home': { phonetic: 'hohm', hint: 'rhymes with "roam"', syllables: ['home'] },

  // Grade 3 words
  'building': { phonetic: 'bil-ding', hint: 'build + ing', syllables: ['build', 'ing'] },
  'creating': { phonetic: 'kree-ay-ting', hint: 'create + ing', syllables: ['cre', 'at', 'ing'] },
  'things': { phonetic: 'thingz', hint: 'thing + z', syllables: ['things'] },
  'bedroom': { phonetic: 'bed-room', hint: 'bed + room', syllables: ['bed', 'room'] },
  'looked': { phonetic: 'lukt', hint: 'look + t', syllables: ['looked'] },
  'workshop': { phonetic: 'werk-shop', hint: 'work + shop', syllables: ['work', 'shop'] },
  'gadgets': { phonetic: 'gaj-its', hint: 'gadget + s', syllables: ['gad', 'gets'] },
  'decided': { phonetic: 'dee-sy-did', hint: 'decide + id', syllables: ['de', 'cid', 'ed'] },
  'build': { phonetic: 'bild', hint: 'rhymes with "filled"', syllables: ['build'] },
  'robot': { phonetic: 'roh-bot', hint: 'row + bot', syllables: ['ro', 'bot'] },
  'helper': { phonetic: 'hel-per', hint: 'help + er', syllables: ['help', 'er'] },
  'collected': { phonetic: 'kuh-lek-tid', hint: 'collect + id', syllables: ['col', 'lect', 'ed'] },
  'parts': { phonetic: 'parts', hint: 'part + s', syllables: ['parts'] },
  'house': { phonetic: 'hous', hint: 'rhymes with "mouse"', syllables: ['house'] },
  'gears': { phonetic: 'geerz', hint: 'gear + z', syllables: ['gears'] },
  'wires': { phonetic: 'wy-erz', hint: 'wire + z', syllables: ['wires'] },
  'buttons': { phonetic: 'but-unz', hint: 'button + z', syllables: ['but', 'tons'] },
  'covered': { phonetic: 'kuv-erd', hint: 'cover + d', syllables: ['cov', 'ered'] },
  'desk': { phonetic: 'desk', hint: 'rhymes with "best"', syllables: ['desk'] },
  'tries': { phonetic: 'tryz', hint: 'try + z', syllables: ['tries'] },
  'finally': { phonetic: 'fy-nuh-lee', hint: 'final + lee', syllables: ['fi', 'nal', 'ly'] },
  'worked': { phonetic: 'werkt', hint: 'work + t', syllables: ['worked'] },
  'because': { phonetic: 'bee-kuz', hint: 'be + cause', syllables: ['be', 'cause'] },
  'sparks': { phonetic: 'sparks', hint: 'spark + s', syllables: ['sparks'] },
  'helped': { phonetic: 'helpt', hint: 'help + t', syllables: ['helped'] },
  'clean': { phonetic: 'kleen', hint: 'rhymes with "mean"', syllables: ['clean'] },
  'room': { phonetic: 'room', hint: 'rhymes with "zoom"', syllables: ['room'] },
  'minutes': { phonetic: 'min-its', hint: 'minute + s', syllables: ['min', 'utes'] },
  'could': { phonetic: 'kud', hint: 'sounds like "good"', syllables: ['could'] },
  'even': { phonetic: 'ee-vin', hint: 'eve + in', syllables: ['e', 'ven'] },
  'bring': { phonetic: 'bring', hint: 'rhymes with "ring"', syllables: ['bring'] },
  'snacks': { phonetic: 'snaks', hint: 'snack + s', syllables: ['snacks'] },
  'kitchen': { phonetic: 'kich-in', hint: 'kitch + in', syllables: ['kitch', 'en'] },
  'became': { phonetic: 'bee-kaym', hint: 'be + came', syllables: ['be', 'came'] },
  'bigger': { phonetic: 'big-er', hint: 'big + er', syllables: ['big', 'ger'] },
  'inventions': { phonetic: 'in-ven-shunz', hint: 'invent + ions', syllables: ['in', 'ven', 'tions'] },
  'knew': { phonetic: 'noo', hint: 'sounds like "new"', syllables: ['knew'] },
  'anything': { phonetic: 'en-ee-thing', hint: 'any + thing', syllables: ['an', 'y', 'thing'] },
  'possible': { phonetic: 'pos-uh-bul', hint: 'poss + ible', syllables: ['pos', 'si', 'ble'] },
  'imagination': { phonetic: 'ih-maj-in-ay-shun', hint: 'imagine + ation', syllables: ['i', 'mag', 'i', 'na', 'tion'] },
  'ancient': { phonetic: 'ayn-shint', hint: 'an + shent', syllables: ['an', 'cient'] },
  'forest': { phonetic: 'for-ist', hint: 'for + ist', syllables: ['for', 'est'] },
  'animals': { phonetic: 'an-ih-mulz', hint: 'animal + z', syllables: ['an', 'i', 'mals'] },
  'harmony': { phonetic: 'har-muh-nee', hint: 'harm + ony', syllables: ['har', 'mo', 'ny'] },
  'terrible': { phonetic: 'tair-uh-bul', hint: 'terror + ible', syllables: ['ter', 'ri', 'ble'] },
  'storm': { phonetic: 'storm', hint: 'rhymes with "warm"', syllables: ['storm'] },
  'threatened': { phonetic: 'thret-ind', hint: 'threaten + d', syllables: ['threat', 'ened'] },
  'woods': { phonetic: 'wudz', hint: 'wood + z', syllables: ['woods'] },
  'thunder': { phonetic: 'thun-der', hint: 'thun + der', syllables: ['thun', 'der'] },
  'crashed': { phonetic: 'krasht', hint: 'crash + t', syllables: ['crashed'] },
  'lightning': { phonetic: 'lyt-ning', hint: 'light + ning', syllables: ['light', 'ning'] },
  'split': { phonetic: 'split', hint: 'rhymes with "hit"', syllables: ['split'] },
  'dark': { phonetic: 'dark', hint: 'rhymes with "park"', syllables: ['dark'] },
  'wise': { phonetic: 'wyz', hint: 'rhymes with "size"', syllables: ['wise'] },
  'owl': { phonetic: 'owl', hint: 'rhymes with "towel"', syllables: ['owl'] },
  'called': { phonetic: 'kawld', hint: 'call + d', syllables: ['called'] },
  'talent': { phonetic: 'tal-int', hint: 'tal + ent', syllables: ['tal', 'ent'] },
  'share': { phonetic: 'shair', hint: 'rhymes with "care"', syllables: ['share'] },
  'beavers': { phonetic: 'bee-verz', hint: 'beaver + z', syllables: ['bea', 'vers'] },
  'built': { phonetic: 'bilt', hint: 'rhymes with "guilt"', syllables: ['built'] },
  'dam': { phonetic: 'dam', hint: 'rhymes with "ham"', syllables: ['dam'] },
  'control': { phonetic: 'kun-trohl', hint: 'con + trol', syllables: ['con', 'trol'] },
  'flooding': { phonetic: 'flud-ing', hint: 'flood + ing', syllables: ['flood', 'ing'] },
  'birds': { phonetic: 'berdz', hint: 'bird + z', syllables: ['birds'] },
  'carried': { phonetic: 'kair-eed', hint: 'carry + d', syllables: ['car', 'ried'] },
  'seeds': { phonetic: 'seedz', hint: 'seed + z', syllables: ['seeds'] },
  'replant': { phonetic: 'ree-plant', hint: 're + plant', syllables: ['re', 'plant'] },
  'damaged': { phonetic: 'dam-ijd', hint: 'damage + d', syllables: ['dam', 'aged'] },
  'areas': { phonetic: 'air-ee-uhz', hint: 'area + z', syllables: ['ar', 'e', 'as'] },
  'squirrels': { phonetic: 'skwer-ulz', hint: 'squirrel + z', syllables: ['squir', 'rels'] },
  'stored': { phonetic: 'stord', hint: 'store + d', syllables: ['stored'] },
  'extra': { phonetic: 'eks-truh', hint: 'ex + tra', syllables: ['ex', 'tra'] },
  'everyone': { phonetic: 'ev-ree-wun', hint: 'every + one', syllables: ['ev', 'ery', 'one'] },
  'deer': { phonetic: 'deer', hint: 'rhymes with "here"', syllables: ['deer'] },
  'led': { phonetic: 'led', hint: 'rhymes with "bed"', syllables: ['led'] },
  'young': { phonetic: 'yung', hint: 'rhymes with "hung"', syllables: ['young'] },
  'safety': { phonetic: 'sayf-tee', hint: 'safe + tee', syllables: ['safe', 'ty'] },
  'passed': { phonetic: 'past', hint: 'sounds like "past"', syllables: ['passed'] },
  'remained': { phonetic: 'ree-maynd', hint: 're + mained', syllables: ['re', 'mained'] },
  'working': { phonetic: 'wer-king', hint: 'work + ing', syllables: ['work', 'ing'] },
  'protected': { phonetic: 'pruh-tek-tid', hint: 'protect + id', syllables: ['pro', 'tect', 'ed'] },
  'their': { phonetic: 'thair', hint: 'sounds like "there"', syllables: ['their'] },
  'strange': { phonetic: 'straynj', hint: 'rhymes with "range"', syllables: ['strange'] },
  'happening': { phonetic: 'hap-in-ing', hint: 'happen + ing', syllables: ['hap', 'pen', 'ing'] },
  'elementary': { phonetic: 'el-uh-men-tree', hint: 'element + ary', syllables: ['el', 'e', 'men', 'tar', 'y'] },
  'items': { phonetic: 'eye-tumz', hint: 'item + z', syllables: ['i', 'tems'] },
  'playground': { phonetic: 'play-ground', hint: 'play + ground', syllables: ['play', 'ground'] },
  'disappeared': { phonetic: 'dis-uh-peerd', hint: 'disappear + d', syllables: ['dis', 'ap', 'peared'] },
  'first': { phonetic: 'ferst', hint: 'rhymes with "worst"', syllables: ['first'] },
  'basketball': { phonetic: 'bas-kit-bawl', hint: 'basket + ball', syllables: ['bas', 'ket', 'ball'] },
  'ropes': { phonetic: 'rohps', hint: 'rope + s', syllables: ['ropes'] },
  'investigate': { phonetic: 'in-ves-ti-gayt', hint: 'invest + igate', syllables: ['in', 'ves', 'ti', 'gate'] },
  'interviewed': { phonetic: 'in-ter-vyood', hint: 'interview + d', syllables: ['in', 'ter', 'viewed'] },
  'students': { phonetic: 'stoo-dints', hint: 'student + s', syllables: ['stu', 'dents'] },
  'careful': { phonetic: 'kair-ful', hint: 'care + ful', syllables: ['care', 'ful'] },
  'notes': { phonetic: 'nohts', hint: 'note + s', syllables: ['notes'] },
  'noticed': { phonetic: 'noh-tist', hint: 'notice + d', syllables: ['no', 'ticed'] },
  'footprints': { phonetic: 'fut-prints', hint: 'foot + prints', syllables: ['foot', 'prints'] },
  'leading': { phonetic: 'lee-ding', hint: 'lead + ing', syllables: ['lead', 'ing'] },
  'toward': { phonetic: 'toh-werd', hint: 'to + ward', syllables: ['to', 'ward'] },
  'shed': { phonetic: 'shed', hint: 'rhymes with "bed"', syllables: ['shed'] },
  'followed': { phonetic: 'fol-ohd', hint: 'follow + d', syllables: ['fol', 'lowed'] },
  'trail': { phonetic: 'trayl', hint: 'rhymes with "tail"', syllables: ['trail'] },
  'missing': { phonetic: 'mis-ing', hint: 'miss + ing', syllables: ['miss', 'ing'] },
  'family': { phonetic: 'fam-uh-lee', hint: 'famil + ee', syllables: ['fam', 'i', 'ly'] },
  'raccoons': { phonetic: 'ra-koonz', hint: 'raccoon + z', syllables: ['rac', 'coons'] },
  'cozy': { phonetic: 'koh-zee', hint: 'rhymes with "rosy"', syllables: ['co', 'zy'] },
  'nest': { phonetic: 'nest', hint: 'rhymes with "best"', syllables: ['nest'] },
  'furry': { phonetic: 'fer-ee', hint: 'fur + ee', syllables: ['fur', 'ry'] },
  'thieves': { phonetic: 'theevz', hint: 'thief + z', syllables: ['thieves'] },
  'collecting': { phonetic: 'kuh-lek-ting', hint: 'collect + ing', syllables: ['col', 'lect', 'ing'] },
  'treasures': { phonetic: 'trezh-erz', hint: 'treasure + z', syllables: ['treas', 'ures'] },
  'principal': { phonetic: 'prin-suh-pul', hint: 'prince + ipal', syllables: ['prin', 'ci', 'pal'] },
  'relocate': { phonetic: 'ree-loh-kayt', hint: 're + locate', syllables: ['re', 'lo', 'cate'] },
  'detective': { phonetic: 'dee-tek-tiv', hint: 'detect + ive', syllables: ['de', 'tec', 'tive'] },
  'hero': { phonetic: 'heer-oh', hint: 'hear + oh', syllables: ['he', 'ro'] },
  'known': { phonetic: 'nohn', hint: 'sounds like "own"', syllables: ['known'] },
  'school': { phonetic: 'skool', hint: 'rhymes with "cool"', syllables: ['school'] },
};

// Get phonetic help for a word
export function getPhoneticHelp(word: string): PhoneticHelp | null {
  const cleanWord = word.toLowerCase().replace(/[^a-z]/g, '');
  return phoneticDictionary[cleanWord] || null;
}

// Generate age-appropriate hint based on grade level
export function getAgeAppropriateHint(word: string, gradeLevel: GradeLevel): string {
  const help = getPhoneticHelp(word);
  if (!help) {
    // Generate basic phonetic breakdown for unknown words
    return word.split('').join(' - ');
  }

  // For younger kids, use simpler explanations
  if (gradeLevel === 'jk' || gradeLevel === 'sk') {
    return help.phonetic;
  }

  // For older kids, include the rhyming hint
  return `${help.phonetic} (${help.hint})`;
}

// Get syllable breakdown for a word
export function getSyllables(word: string): string[] {
  const help = getPhoneticHelp(word);
  if (!help) {
    // Basic syllable guess for unknown words
    return [word];
  }
  return help.syllables;
}

// Check if a word is in our dictionary
export function hasPhoneticData(word: string): boolean {
  const cleanWord = word.toLowerCase().replace(/[^a-z]/g, '');
  return cleanWord in phoneticDictionary;
}
